version: '3'
services:

  proxy:
    image: nginx:mainline-alpine
    ports:
      - "3000:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./assets:/var/www/html/assets:ro"
    networks:
      - webnet

  website:
    hostname: website
    image: ${REPO:?err}/website:1.0.0
    networks:
      - webnet

  renderer:
    hostname: renderer
    image: ${REPO:?err}/renderer:1.0.0
    env_file:
      - renderer.env
    networks:
      - intranet

  login:
    hostname: login
    image: ${REPO:?err}/login:1.0.0
    env_file:
      - login.env
    networks:
      - webnet
      - intranet

  user:
    hostname: user
    image: ${REPO:?err}/user:1.0.0
    env_file:
      - user.env
    networks:
      - webnet

  email:
    hostname: email
    image: ${REPO:?err}/email:1.0.0
    env_file:
      - email.env
    networks:
      - intranet

  post:
    hostname: post
    image: ${REPO:?err}/post:1.0.0
    env_file:
      - post.env
    networks:
      - webnet
      - intranet

  msgstore:
    hostname: msgstore
    image: ipfs/go-ipfs:release
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    volumes:
      - "msgdata:/data/ipfs"
      - "msgexport:/export"
    networks:
      - intranet

volumes:

  msgdata:
  msgexport:

networks:

  intranet:
    driver: overlay

  webnet:
    driver: overlay

