apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    project: cast
spec:
  selector:
    matchLabels:
      name: proxy
      project: cast
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: proxy
        project: cast
    spec:
      containers:
      - image: nginx:mainline-alpine
        name: proxy
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      restartPolicy: Always
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
