apiVersion: v1
data:
  NAME: renderer
  ADDRESS: :3000
  DPI: "72"
  FONTFILE: fonts/NotoSans-Regular.ttf
  IPFS_ADDRESS: localhost:5001
  ROOT_URL: http://localhost
kind: ConfigMap
metadata:
  name: renderer-env
  labels:
    project: cast
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: renderer
  labels:
    project: cast
spec:
  selector:
    matchLabels:
      name: renderer
      project: cast
  replicas: 1
  template:
    metadata:
      labels:
        name: renderer
        project: cast
    spec:
      containers:
      - env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              key: NAME
              name: renderer-env
        - name: ADDRESS
          valueFrom:
            configMapKeyRef:
              key: ADDRESS
              name: renderer-env
        - name: DPI
          valueFrom:
            configMapKeyRef:
              key: DPI
              name: renderer-env
        - name: FONTFILE
          valueFrom:
            configMapKeyRef:
              key: FONTFILE
              name: renderer-env
        - name: IPFS_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: IPFS_ADDRESS
              name: renderer-env
        - name: ROOT_URL
          valueFrom:
            configMapKeyRef:
              key: ROOT_URL
              name: renderer-env
        image: ${REPO}/renderer
        imagePullPolicy: IfNotPresent
        name: renderer
        ports:
        - containerPort: 3000
      hostname: renderer
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: renderer
  labels:
    project: cast
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 3000
  selector:
    name: renderer
    project: cast
